#! /bin/sh

sxhkd &
~/.config/polybar/launch.sh
polybar main &
picom -b --config ~/.config/picom/picom.conf
feh --bg-scale ~/.config/walls/walltest.png
~scripts/spotify/launchlistener.sh

bspc monitor -d 1 2 3 4 5

bspc config border_width       2
bspc config window_gap         8
bspc config top_padding        36
bspc config bottom_padding     0
bspc config left_padding       8
bspc config right_padding      8

# Border colors
bspc config normal_border_color "#263238"
bspc config focused_border_color "#5e81ac"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
